import { Fragment } from 'react';
import Head from 'next/head';

interface LayoutProps {
  title: string;
  children: React.ReactNode;
}

const Layout = ({ title, children }: LayoutProps) => {
  return (
    <Fragment>
      <Head>
        <title>{title}</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <div className='mx-auto p-4 bg-gradient-to-t from-gray-700 via-gray-900 to-black'>
        <h1 className='text-white text-5xl text-center'>Pokedex Next</h1>
      </div>
      <main className='container mx-auto pt-8 min-h-screen'>{children}</main>
    </Fragment>
  );
};

export default Layout;
